### ISSUE TITLE
Compiler errors on building player

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/NavMeshComponents#65] opened 2018-02-08 02:13 UTC
these errors only show up when attempting to build the player:

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceAgentTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceAgentTests.cs Line: 4)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceAgentTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceAgentTests.cs Line: 5)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceLinkTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceLinkTests.cs Line: 4)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceLinkTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceLinkTests.cs Line: 5)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierTests.cs Line: 4)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierTests.cs Line: 5)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierVolumeTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierVolumeTests.cs Line: 4)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierVolumeTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierVolumeTests.cs Line: 5)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceTests.cs Line: 4)

Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/NavMeshComponenets/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceTests.cs Line: 5)

**Comment by turadr** [comment] 2018-02-08 13:41
Thanks, we'll check that. 
Just to make sure, do you use the right branch that matches your Unity editor's version? Which version is that?

**Comment by turadr** [comment] 2021-01-28 12:10
This issue has probably been fixed in the meantime because I cannot reproduce it anymore.

**Closed by turadr** 2021-01-28 12:10 UTC
Labels: bug
